// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrWMGeCD1xip7qJC9fy4qPDhSmzlVdUY',
    appId: '1:152988047457:web:9672653b708bb86b33f220',
    messagingSenderId: '152988047457',
    projectId: 'packinn-d136c',
    authDomain: 'packinn-d136c.firebaseapp.com',
    storageBucket: 'packinn-d136c.firebasestorage.app',
    measurementId: 'G-TY2N23Y7BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKi-nmeOnNvRgAuCCRFi8TU2_RrpsdOf0',
    appId: '1:152988047457:android:5a075169aa09498f33f220',
    messagingSenderId: '152988047457',
    projectId: 'packinn-d136c',
    storageBucket: 'packinn-d136c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnM_3Ngq-x4nJ65jTBhRTDNfFNg-rk7mQ',
    appId: '1:152988047457:ios:737a9ffcf93361b033f220',
    messagingSenderId: '152988047457',
    projectId: 'packinn-d136c',
    storageBucket: 'packinn-d136c.firebasestorage.app',
    iosBundleId: 'com.example.packinn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnM_3Ngq-x4nJ65jTBhRTDNfFNg-rk7mQ',
    appId: '1:152988047457:ios:737a9ffcf93361b033f220',
    messagingSenderId: '152988047457',
    projectId: 'packinn-d136c',
    storageBucket: 'packinn-d136c.firebasestorage.app',
    iosBundleId: 'com.example.packinn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsrWMGeCD1xip7qJC9fy4qPDhSmzlVdUY',
    appId: '1:152988047457:web:c80c115e56cc876c33f220',
    messagingSenderId: '152988047457',
    projectId: 'packinn-d136c',
    authDomain: 'packinn-d136c.firebaseapp.com',
    storageBucket: 'packinn-d136c.firebasestorage.app',
    measurementId: 'G-WR7DW91SQ2',
  );
}
